version: '2.2'

services:
  uam_1:
    image: debian:bullseye-slim
    container_name: uam_1
    hostname: uam_1
    restart: always
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    tmpfs:
      - /root/.uam:size=1000m
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17100:17099"
      - "4160:4160"
    environment:
      - PBKEY=${PBKEY}
      - PPORT=4160
      - NETLIMUP=10000
      - NETLIMDOWN=18000

  uam_2:
    image: debian:bullseye-slim
    container_name: uam_2
    hostname: uam_2
    restart: always
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    tmpfs:
      - /root/.uam:size=1000m
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17101:17099"
      - "4161:4161"
    environment:
      - PBKEY=${PBKEY}
      - PPORT=4161
      - NETLIMUP=10000
      - NETLIMDOWN=18000

  uam_3:
    image: debian:bullseye-slim
    container_name: uam_3
    hostname: uam_3
    restart: always
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    tmpfs:
      - /root/.uam:size=1000m
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17102:17099"
      - "4162:4162"
    environment:
      - PBKEY=${PBKEY}
      - PPORT=4162
      - NETLIMUP=10000
      - NETLIMDOWN=18000

  uam_4:
    image: debian:bullseye-slim
    container_name: uam_4
    hostname: uam_4
    restart: always
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    tmpfs:
      - /root/.uam:size=1000m
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17103:17099"
      - "4163:4163"
    environment:
      - PBKEY=${PBKEY}
      - PPORT=4163
      - NETLIMUP=10000
      - NETLIMDOWN=18000

  uam_5:
    image: debian:bullseye-slim
    container_name: uam_5
    hostname: uam_5
    restart: always
    stop_grace_period: 5s
    cap_add:
      - NET_ADMIN
    ulimits:
      rtprio: 95
      memlock: -1
    oom_score_adj: -700
    mem_swappiness: 10
    tmpfs:
      - /root/.uam:size=1000m
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY} $${PPORT} $${NETLIMUP} $${NETLIMDOWN}"
    ports:
      - "127.0.0.1:17104:17099"
      - "4164:4164"
    environment:
      - PBKEY=${PBKEY}
      - PPORT=4164
      - NETLIMUP=10000
      - NETLIMDOWN=18000
